[pytest]
filterwarnings =
    ignore:Passing more than 2 positional arguments to np.maximum and np.minimum is deprecated.*:DeprecationWarning
    ignore:Using `httpx` with `starlette.testclient` is deprecated.*:DeprecationWarning
    ignore:The anyio.abc.BlockingPortal alias is deprecated.*:DeprecationWarning